// Video 4 · Cari ve Finans Şeffaflığı (hedef ≈ 45 sn)
const VIDEO = {
  id: 'V4', music: 'promo', musicVol: 0.34, tail: 1.0, pace: 1.4,
  scenes: [
    { type: 'title', d: 4.2, eyebrow: 'Cari ve finans', size: 140, y: 330,
      lines: [{ t: 'Bakiyeniz kaç?' }, { t: 'Vadesi ne zaman?', accent: true }],
      vo: [{ id: 'v4-01', text: 'Bakiyeniz, vadeniz, faturalarınız… hepsi tek yerde.' }] },
    { type: 'explain', d: 6.5, eyebrow: 'Finans', title: ['tek ekranda.'],
      items: [{ icon: 'wallet', t: 'Açık bakiye', d: 'Vade dilimleriyle.' }, { icon: 'doc', t: 'e-Fatura', d: 'Logo ERP’den otomatik.' }, { icon: 'chart', t: 'Analitik', d: 'Harcama nereye gidiyor?' }, { icon: 'star', t: 'Sadakat', d: 'Her siparişte puan.' }],
      vo: [{ id: 'v4-x', text: 'Bakiye, fatura, analitik ve sadakat; hepsi tek ekranda.', at: 0.9 }] },
    { type: 'screen', shot: 'ekstre', d: 6, head: { eb: 'Cari Ekstre', ttl: 'Açık bakiye ve vade dilimleri' },
      cam: [{ at: 0.8, rect: { x: 566, y: 300, w: 1070, h: 150 }, pad: 50 }],
      focus: [{ at: 1.4, end: 3.3, rect: { x: 566, y: 376, w: 256, h: 64 }, label: 'Açık bakiye', desc: 'Henüz ödenmemiş toplam tutar.', pad: 6 },
              { at: 3.3, rect: { x: 838, y: 376, w: 796, h: 64 }, label: '0–30 · 31–60 · 60+ gün', desc: 'Borcunuzun hangi vade aralığında olduğunu gösterir; 60+ boşsa gecikme yok.', pad: 6 }],
      vo: [{ id: 'v4-02', text: 'Açık bakiyenizi ve vade dilimlerini tek bakışta görün.', at: 1.0 }] },
    { type: 'screen', shot: 'ekstre-alt', d: 5.5, head: { eb: 'Hareketler', ttl: 'Sipariş, tahsilat, fatura' },
      cam: [{ at: 0.8, rect: { x: 566, y: 200, w: 1070, h: 500 }, pad: 10 }],
      focus: [{ at: 1.4, rect: { x: 818, y: 198, w: 100, h: 30 }, label: 'Tahsilat', desc: 'Ödemeniz alındığında alacak olarak işlenir.', pad: 6 }],
      vo: [{ id: 'v4-03', text: 'Her sipariş, tahsilat ve fatura hareketi vadesiyle birlikte listelenir.', at: 1.0 }] },
    { type: 'screen', shot: 'faturalar', d: 5, head: { eb: 'Faturalarım', ttl: 'e-Fatura, Logo ERP’den otomatik' },
      cam: [{ at: 0.8, rect: { x: 565, y: 220, w: 1072, h: 220 }, pad: 40 }],
      focus: [{ at: 1.4, key: 'logo', label: 'Logo ERP entegrasyonu', desc: 'Faturalar ERP’den otomatik gelir; elle işlem yok.', pad: 8 }],
      vo: [{ id: 'v4-04', text: 'Faturalarınız Logo ERP üzerinden otomatik düzenlenir; tek tıkla indirin.', at: 1.0 }] },
    { type: 'screen', shot: 'analitik', d: 6, head: { eb: 'Satın Alma Analitiği', ttl: 'Son 12 ayın özeti' },
      cam: [{ at: 0.8, rect: { x: 566, y: 290, w: 1070, h: 590 }, pad: 10 }],
      focus: [{ at: 1.4, end: 3.4, rect: { x: 566, y: 300, w: 1070, h: 66 }, label: 'Harcama · ortalama sepet · indirim', desc: 'Son 12 ayın satın alma özeti.', pad: 4 },
              { at: 3.4, rect: { x: 566, y: 620, w: 524, h: 250 }, label: 'Kategori dağılımı', desc: 'Harcamanızın hangi ürün grubuna gittiği.', pad: 4 }],
      vo: [{ id: 'v4-05', text: 'Satın alma analitiğiyle harcamanızın nereye gittiğini görün.', at: 1.0 }] },
    { type: 'screen', shot: 'sadakat', d: 5, head: { eb: 'Sadakat Programı', ttl: 'Her siparişte puan' },
      cam: [{ at: 0.8, rect: { x: 566, y: 300, w: 1070, h: 320 }, pad: 20 }],
      focus: [{ at: 1.4, rect: { x: 572, y: 380, w: 230, h: 90 }, label: 'Altın müşteri · 49.833 puan', desc: 'Kademeniz ve toplam puan bakiyeniz.', pad: 6 }],
      vo: [{ id: 'v4-06', text: 'Her siparişte puan kazanın, kupona çevirin.', at: 1.0 }] },
    { type: 'end', d: 4, vo: [{ id: 'v4-07', text: 'MTS Hijyen B2B. Şeffaf cari, kontrollü harcama.' }] },
  ],
};
if (typeof module !== 'undefined') module.exports = VIDEO;
