// Çekilecek ekranlar. once: sayfa açıldıktan sonra yapılacak görüntüleme adımı (form açmak, kaydırmak, yazı yazmak).
const kaydir = (y) => async (p) => { await p.evaluate((y) => window.scrollTo(0, y), y); await p.waitForTimeout(700); };
// Sayfada metni içeren başlığa kaydır (ofset: başlığın üstünde bırakılacak boşluk)
const bul = (metin, ofset = -100) => async (p) => {
  await p.evaluate(([m, o]) => { const el = [...document.querySelectorAll('h1,h2,h3,h4,legend,button,summary,div')].find((e) => e.childElementCount < 4 && (e.innerText || '').trim().startsWith(m));
    if (el) window.scrollTo(0, el.getBoundingClientRect().top + scrollY + o); }, [metin, ofset]); await p.waitForTimeout(800); };
const tikla = (metin) => async (p) => { await p.click(`text=${metin}`); await p.waitForTimeout(1500); };
module.exports = [
  // Mağaza
  { ad: 'giris', url: '/tr/giris', misafir: true },
  { ad: 'anasayfa', url: '/tr' },
  { ad: 'anasayfa-alt', url: '/tr', once: kaydir(900) },
  { ad: 'arama', url: '/tr', once: async (p) => { await p.click('input[placeholder*="SKU"]'); await p.keyboard.type('kağıt havlu', { delay: 50 }); await p.waitForTimeout(2500); } },
  { ad: 'kategori', url: '/tr/c/kagit-urunleri' },
  { ad: 'urun', url: '/tr/p/fotoselli-sensorlu-kagit-havlu-4-kg' },
  { ad: 'urun-alt', url: '/tr/p/fotoselli-sensorlu-kagit-havlu-4-kg', once: kaydir(700) },
  { ad: 'sepet', url: '/tr/sepet' },
  { ad: 'kampanyalar', url: '/tr/kampanyalar' },
  { ad: 'teklif-iste', url: '/tr/teklif-iste' },
  { ad: 'yardim', url: '/tr/yardim' },
  // Hesap
  { ad: 'ozet', url: '/tr/hesap/ozet' },
  { ad: 'ozet-alt', url: '/tr/hesap/ozet', once: kaydir(560) },
  { ad: 'siparisler', url: '/tr/hesap/siparisler' },
  { ad: 'siparis-hazirlaniyor', url: '/tr/hesap/siparisler/cmuwo1euv004b60vgufnvgnaz' },
  { ad: 'siparis-hazirlaniyor-alt', url: '/tr/hesap/siparisler/cmuwo1euv004b60vgufnvgnaz', once: kaydir(420) },
  { ad: 'siparis-taslak', url: '/tr/hesap/siparisler/cmuwo1i5v005w60vgu5fo3x2j' },
  { ad: 'siparis-odeme', url: '/tr/hesap/siparisler/cmuwo1htm005r60vg3687u49q' },
  { ad: 'siparis-onay', url: '/tr/hesap/siparisler/cmuwo1hhi005n60vgz9ty3fhl' },
  { ad: 'siparis-sevkiyat', url: '/tr/hesap/siparisler/cmuwo1dte003t60vgrstxfcbf' },
  { ad: 'hizli', url: '/tr/hesap/hizli-siparis' },
  { ad: 'periyodik', url: '/tr/hesap/periyodik-siparisler' },
  { ad: 'periyodik-yeni', url: '/tr/hesap/periyodik-siparisler/yeni' },
  { ad: 'teklifler', url: '/tr/hesap/teklifler', ortu: ['[]TKF-2026-0002'] },   // test kaydı (525.000 ₺)
  { ad: 'teklif-yeni', url: '/tr/hesap/teklifler/yeni' },
  { ad: 'analitik', url: '/tr/hesap/analitik', bekle: 3000 },
  { ad: 'analitik-alt', url: '/tr/hesap/analitik', bekle: 3000, once: kaydir(560) },
  { ad: 'sozlesme', url: '/tr/hesap/sozlesme' },
  { ad: 'butce', url: '/tr/hesap/butce', ortu: ['CUSTOMER MANAGER', 'CUSTOMER MANAGER#2'] },   // ham rol kodu
  { ad: 'butce-alt', url: '/tr/hesap/butce', once: kaydir(380), ortu: ['CUSTOMER MANAGER', 'CUSTOMER MANAGER#2'] },
  { ad: 'onaylarim', url: '/tr/hesap/onaylarim' },
  { ad: 'onay-kurallari', url: '/tr/hesap/onay-kurallari' },
  { ad: 'onay-kural-yeni', url: '/tr/hesap/onay-kurallari', once: tikla('+ Yeni Kural') },
  { ad: 'ekstre', url: '/tr/hesap/ekstre' },
  { ad: 'ekstre-alt', url: '/tr/hesap/ekstre', once: kaydir(380) },
  { ad: 'faturalar', url: '/tr/hesap/faturalar' },
  { ad: 'kullanicilar', url: '/tr/hesap/kullanicilar' },
  { ad: 'kullanici-davet', url: '/tr/hesap/kullanicilar/davet' },
  { ad: 'departmanlar', url: '/tr/hesap/departmanlar' },
  { ad: 'departman-yeni', url: '/tr/hesap/departmanlar', once: tikla('+ Yeni Departman') },
  { ad: 'projeler', url: '/tr/hesap/projeler' },
  { ad: 'proje-yeni', url: '/tr/hesap/projeler', once: tikla('Yeni Proje') },
  { ad: 'adresler', url: '/tr/hesap/adresler' },
  { ad: 'listeler', url: '/tr/hesap/listeler' },
  { ad: 'listeler-firma', url: '/tr/hesap/listeler?tab=COMPANY' },
  { ad: 'favoriler', url: '/tr/hesap/favoriler' },
  { ad: 'iadeler', url: '/tr/hesap/iadeler' },
  { ad: 'numune', url: '/tr/hesap/numune-talepler' },
  { ad: 'numune-yeni', url: '/tr/numune-talep' },
  { ad: 'ai-oneri', url: '/tr/hesap/ai-oneri', bekle: 2500 },
  { ad: 'sadakat', url: '/tr/hesap/sadakat' },
  { ad: 'sadakat-alt', url: '/tr/hesap/sadakat', once: kaydir(560) },
  { ad: 'kuponlar', url: '/tr/hesap/kuponlar' },
  { ad: 'davet', url: '/tr/hesap/davet' },
  { ad: 'bildirimler', url: '/tr/hesap/bildirimler' },
  { ad: 'destek', url: '/tr/hesap/destek' },
  { ad: 'destek-yeni', url: '/tr/hesap/destek/yeni' },
  { ad: 'ayarlar', url: '/tr/hesap/ayarlar' },
  { ad: 'ayarlar-alt', url: '/tr/hesap/ayarlar', once: kaydir(560) },
  // 2026-10-09 eklenenler (yalnızca görüntüleme)
  { ad: 'katalog', url: '/tr/katalog' },
  { ad: 'katalog-tekrar', url: '/tr/katalog?ben=1' },
  { ad: 'katalog-hacim', url: '/tr/katalog?bulk=1' },
  { ad: 'arama-sonuc', url: '/tr/katalog?q=havlu' },
  { ad: 'alt-kategori', url: '/tr/c/kagit-havlu' },
  { ad: 'urun-tukendi', url: '/tr/p/maxi-cimri-tuvalet-kagidi-6-kg-222-m-6-li-paket' },
  { ad: 'urun-teknik', url: '/tr/p/fotoselli-sensorlu-kagit-havlu-4-kg', once: bul('Teknik Özellikler', -90) },
  { ad: 'paketler', url: '/tr/paketler' },
  { ad: 'paket-ofis', url: '/tr/paket/ofis-baslangic-paketi' },
  { ad: 'paket-otel', url: '/tr/paket/otel-housekeeping-paketi' },
  { ad: 'paket-okul', url: '/tr/paket/okul-egitim-kurumu-paketi' },
  { ad: 'paket-restoran', url: '/tr/paket/restoran-mutfak-hijyen-paketi' },
  { ad: 'paket-mutfak', url: '/tr/paket/ofis-mutfagi-bulasik-makinesi-seti' },
  { ad: 'karsilastir', url: '/tr/karsilastir?ids=cmu3qg8a0001n22qw26vhe07l,cmu3qg898001f22qwv56gdcw7,cmtcty62r01ve58vgsrbpgkes' },
  { ad: 'teklif-hazir', url: '/tr/hesap/teklifler/cmuwo1owi008d60vgaw8eecju' },
  { ad: 'teklif-gonderildi', url: '/tr/hesap/teklifler/cmuwo1p54008i60vgle64ydxy' },
  { ad: 'siparis-teslim', url: '/tr/hesap/siparisler/cmuwo1d8n003j60vgry4kpe3n' },
  { ad: 'siparis-teslim-kargo', url: '/tr/hesap/siparisler/cmuwo1d8n003j60vgry4kpe3n', once: bul('Sevkiyat', -120) },
  { ad: 'siparis-degerlendir', url: '/tr/hesap/siparisler/cmuwo1d8n003j60vgry4kpe3n', once: bul('Ürünleri Değerlendir', -120) },
  { ad: 'siparis-reddedildi', url: '/tr/hesap/siparisler/cmuwo1bnd002q60vgwu0trmnv' },
  { ad: 'siparis-yazdir', url: '/tr/hesap/siparisler/cmuwo1euv004b60vgufnvgnaz/yazdir' },
  { ad: 'siparis-mts-bekleniyor', url: '/tr/hesap/siparisler/cmuwo1gak005160vgp6xmlb5h' },
  { ad: 'iade-yeni', url: '/tr/hesap/iadeler/yeni?order=cmuwo1d8n003j60vgry4kpe3n' },
  { ad: 'kullanici-yetki', url: '/tr/hesap/kullanicilar/cmuwo1688000460vgpcfvvij3' },
  { ad: 'kullanici-yetki-alt', url: '/tr/hesap/kullanicilar/cmuwo1688000460vgpcfvvij3', once: bul('Detaylı Yetkiler', -120) },
  { ad: 'sadakat-puan', url: '/tr/hesap/sadakat', once: bul('Puan Kullan', -120) },
  { ad: 'ayarlar-bildirim', url: '/tr/hesap/ayarlar', once: bul('Bildirim Tercihleri', -120) },
  { ad: 'bildirim-panel', url: '/tr/hesap/ozet', once: async (p) => { await p.click('button[aria-label^="Bildirimler"]'); await p.waitForTimeout(1200); } },
  { ad: 'hesap-menu', url: '/tr/hesap/ozet', once: async (p) => { await p.click('button[aria-label^="Hesap menüsü"]'); await p.waitForTimeout(1200); } },
  { ad: 'kayit', url: '/tr/kayit', misafir: true },
  { ad: 'sifremi-unuttum', url: '/tr/sifremi-unuttum', misafir: true },
  // Mobil (430 px, DPR 3): telefon sahneleri için
  { ad: 'm-ozet', url: '/tr/hesap/ozet', mobil: true, boy: 2000 },
  { ad: 'm-siparisler', url: '/tr/hesap/siparisler', mobil: true, boy: 2000 },
  { ad: 'm-siparis-sevkiyat', url: '/tr/hesap/siparisler/cmuwo1dte003t60vgrstxfcbf', mobil: true, boy: 2200 },
  { ad: 'm-onaylarim', url: '/tr/hesap/onaylarim', mobil: true, boy: 1800 },
  { ad: 'm-hizli', url: '/tr/hesap/hizli-siparis', mobil: true, boy: 932 },
  { ad: 'm-periyodik', url: '/tr/hesap/periyodik-siparisler', mobil: true, boy: 1600 },
  { ad: 'm-sadakat', url: '/tr/hesap/sadakat', mobil: true, boy: 1600 },
  { ad: 'm-faturalar', url: '/tr/hesap/faturalar', mobil: true, boy: 600 },
  { ad: 'm-ekstre', url: '/tr/hesap/ekstre', mobil: true, boy: 1600 },
  { ad: 'm-butce', url: '/tr/hesap/butce', mobil: true, boy: 700 },
  { ad: 'm-kategori', url: '/tr/c/kagit-urunleri', mobil: true, boy: 1800 },
  { ad: 'm-urun', url: '/tr/p/fotoselli-sensorlu-kagit-havlu-4-kg', mobil: true, boy: 1800 },
  // Menüler: yalnızca açılır menü düğmesine dokunulur, içindeki bağlantılara basılmaz
  { ad: 'm-teklifler', url: '/tr/hesap/teklifler', mobil: true, boy: 1400, ortu: ['[]TKF-2026-0002'] },
  { ad: 'm-teklif-hazir', url: '/tr/hesap/teklifler/cmuwo1owi008d60vgaw8eecju', mobil: true, boy: 2000 },
  { ad: 'm-analitik', url: '/tr/hesap/analitik', mobil: true, boy: 2000 },
  { ad: 'm-sozlesme', url: '/tr/hesap/sozlesme', mobil: true, boy: 1800 },
  { ad: 'm-onay-kurallari', url: '/tr/hesap/onay-kurallari', mobil: true, boy: 1600 },
  { ad: 'm-kullanicilar', url: '/tr/hesap/kullanicilar', mobil: true, boy: 1600 },
  { ad: 'm-departmanlar', url: '/tr/hesap/departmanlar', mobil: true, boy: 1600 },
  { ad: 'm-projeler', url: '/tr/hesap/projeler', mobil: true, boy: 1600 },
  { ad: 'm-listeler', url: '/tr/hesap/listeler', mobil: true, boy: 1400 },
  { ad: 'm-favoriler', url: '/tr/hesap/favoriler', mobil: true, boy: 1600 },
  { ad: 'm-iadeler', url: '/tr/hesap/iadeler', mobil: true, boy: 1600 },
  { ad: 'm-iade-yeni', url: '/tr/hesap/iadeler/yeni?order=cmuwo1d8n003j60vgry4kpe3n', mobil: true, boy: 1800 },
  { ad: 'm-numune', url: '/tr/hesap/numune-talepler', mobil: true, boy: 1200 },
  { ad: 'm-kuponlar', url: '/tr/hesap/kuponlar', mobil: true, boy: 1400 },
  { ad: 'm-davet', url: '/tr/hesap/davet', mobil: true, boy: 1600 },
  { ad: 'm-bildirimler', url: '/tr/hesap/bildirimler', mobil: true, boy: 1600 },
  { ad: 'm-destek', url: '/tr/hesap/destek', mobil: true, boy: 1200 },
  { ad: 'm-ayarlar', url: '/tr/hesap/ayarlar', mobil: true, boy: 2000 },
  { ad: 'm-kampanyalar', url: '/tr/kampanyalar', mobil: true, boy: 2000 },
  { ad: 'm-paketler', url: '/tr/paketler', mobil: true, boy: 2000 },
  { ad: 'm-paket-ofis', url: '/tr/paket/ofis-baslangic-paketi', mobil: true, boy: 2000 },
  { ad: 'm-katalog-tekrar', url: '/tr/katalog?ben=1', mobil: true, boy: 1800 },
  { ad: 'm-siparis-teslim', url: '/tr/hesap/siparisler/cmuwo1d8n003j60vgry4kpe3n', mobil: true, boy: 2200 },
  { ad: 'm-siparis-odeme', url: '/tr/hesap/siparisler/cmuwo1htm005r60vg3687u49q', mobil: true, boy: 2000 },
  { ad: 'm-yardim', url: '/tr/yardim', mobil: true, boy: 1800 },
  { ad: 'm-giris', url: '/tr/giris', mobil: true, misafir: true, boy: 932 },
  { ad: 'm-menu-hesap', url: '/tr/hesap/ozet', mobil: true, boy: 932, once: async (p) => { await p.click('button[aria-label^="Hesap menüsü"]'); await p.waitForTimeout(900); } },
  { ad: 'm-menu-bolum', url: '/tr/hesap/ozet', mobil: true, boy: 1400, once: async (p) => {
    await p.evaluate(() => [...document.querySelectorAll('button')].find((b) => /^Özet/.test(b.innerText.trim()))?.click()); await p.waitForTimeout(900); } },
];

// Menü yolu: videoda tarayıcı çubuğunda "konum çipi" olarak görünür (müşteri ekranı nereden açacağını görür)
const H = (b) => `Hesabım › ${b}`;
const YOL = {
  anasayfa: 'Ana sayfa', 'anasayfa-alt': 'Ana sayfa', arama: 'Ana sayfa › Arama', kategori: 'Kategoriler › Kağıt Ürünleri',
  urun: 'Kağıt Ürünleri › Ürün', 'urun-alt': 'Kağıt Ürünleri › Ürün', sepet: 'Sepetim', kampanyalar: 'Vitrin › Kampanyalar',
  'teklif-iste': 'Kurumsal › Teklif İste', yardim: 'Kurumsal › Yardım',
  ozet: H('Özet'), 'ozet-alt': H('Özet'), siparisler: H('Siparişlerim'),
  'siparis-hazirlaniyor': 'Siparişlerim › Detay', 'siparis-hazirlaniyor-alt': 'Siparişlerim › Detay', 'siparis-taslak': 'Siparişlerim › Detay',
  'siparis-odeme': 'Siparişlerim › Detay', 'siparis-onay': 'Siparişlerim › Detay', 'siparis-sevkiyat': 'Siparişlerim › Detay',
  hizli: H('Hızlı Sipariş'), periyodik: H('Periyodik Siparişler'), 'periyodik-yeni': H('Periyodik Siparişler'),
  teklifler: H('Fiyat Tekliflerim'), 'teklif-yeni': H('Fiyat Tekliflerim'), analitik: H('Analitik'), 'analitik-alt': H('Analitik'),
  sozlesme: H('Sözleşme & Fiyat'), butce: H('Bütçe Panosu'), 'butce-alt': H('Bütçe Panosu'), onaylarim: H('Onaylarım'),
  'onay-kurallari': H('Onay Kuralları'), 'onay-kural-yeni': H('Onay Kuralları'), ekstre: H('Cari Ekstre'), 'ekstre-alt': H('Cari Ekstre'),
  faturalar: H('Faturalarım'), kullanicilar: H('Kullanıcılar & Yetkiler'), 'kullanici-davet': H('Kullanıcılar & Yetkiler'),
  departmanlar: H('Departman & Bütçe'), 'departman-yeni': H('Departman & Bütçe'), projeler: H('Projeler / Şantiyeler'), 'proje-yeni': H('Projeler / Şantiyeler'),
  adresler: H('Adres Defteri'), listeler: H('Sipariş Listelerim'), 'listeler-firma': H('Sipariş Listelerim'), favoriler: H('Favorilerim'),
  iadeler: H('İade Taleplerim'), numune: H('Numune Taleplerim'), 'numune-yeni': H('Numune Taleplerim'), 'ai-oneri': H('AI Ürün Asistanı'),
  sadakat: H('Sadakat Programı'), 'sadakat-alt': H('Sadakat Programı'), kuponlar: H('Kuponlarım'), davet: H('Arkadaşını Davet Et'),
  katalog: 'Ana sayfa › Tüm Ürünler', 'katalog-tekrar': 'Tüm Ürünler › Önceden aldıklarım', 'katalog-hacim': 'Tüm Ürünler › Hacim indirimi',
  'arama-sonuc': 'Arama › Sonuçlar', 'alt-kategori': 'Kağıt Ürünleri › Kağıt Havlu', 'urun-tukendi': 'Kağıt Ürünleri › Ürün', 'urun-teknik': 'Kağıt Ürünleri › Ürün',
paketler: 'Vitrin › Paketler', 'paket-ofis': 'Paketler › Ofis Başlangıç', 'paket-otel': 'Paketler › Otel Housekeeping',
  'paket-okul': 'Paketler › Okul & Eğitim', 'paket-restoran': 'Paketler › Restoran & Mutfak', 'paket-mutfak': 'Paketler › Ofis Mutfağı', karsilastir: 'Ürün Karşılaştırma',
  'teklif-hazir': 'Fiyat Tekliflerim › Detay', 'teklif-gonderildi': 'Fiyat Tekliflerim › Detay', 'siparis-teslim': 'Siparişlerim › Detay', 'siparis-teslim-kargo': 'Siparişlerim › Detay',
  'siparis-degerlendir': 'Siparişlerim › Detay', 'siparis-reddedildi': 'Siparişlerim › Detay', 'siparis-yazdir': 'Siparişlerim › Yazdır', 'iade-yeni': 'İade Taleplerim › Yeni',
  'kullanici-yetki': 'Kullanıcılar & Yetkiler › Düzenle', 'kullanici-yetki-alt': 'Kullanıcılar & Yetkiler › Düzenle', 'sadakat-puan': H('Sadakat Programı'),
  'ayarlar-bildirim': H('Ayarlar'), 'bildirim-panel': 'Üst menü › Bildirimler', 'hesap-menu': 'Üst menü › Hesabım', kayit: 'Kurumsal Üyelik', 'sifremi-unuttum': 'Giriş › Şifremi unuttum',
  'siparis-odeme': 'Siparişlerim › Detay', 'siparis-mts-bekleniyor': 'Siparişlerim › Detay', giris: 'Giriş',
  bildirimler: H('Bildirimler'), destek: H('Destek'), 'destek-yeni': H('Destek'), ayarlar: H('Ayarlar'), 'ayarlar-alt': H('Ayarlar'),
};
module.exports.forEach((e) => { const y = YOL[e.ad] || YOL[e.ad.replace(/^m-/, '')]; if (y) e.yol = y; });
