// Çekilecek ekranlar. once: sayfa açıldıktan sonra yapılacak görüntüleme adımı (form açmak, kaydırmak, yazı yazmak).
const kaydir = (y) => async (p) => { await p.evaluate((y) => window.scrollTo(0, y), y); await p.waitForTimeout(700); };
const tikla = (metin) => async (p) => { await p.click(`text=${metin}`); await p.waitForTimeout(1500); };
module.exports = [
  // Mağaza
  { ad: 'giris', url: '/tr/giris', misafir: true },
  { ad: 'anasayfa', url: '/tr' },
  { ad: 'anasayfa-alt', url: '/tr', once: kaydir(900) },
  { ad: 'arama', url: '/tr', once: async (p) => { await p.click('input[placeholder*="SKU"]'); await p.keyboard.type('kağıt havlu', { delay: 50 }); await p.waitForTimeout(2500); } },
  { ad: 'kategori', url: '/tr/c/kagit-urunleri' },
  { ad: 'urun', url: '/tr/p/wanda-soft-extra-automotion-kagit-havlu-4-kg' },
  { ad: 'urun-alt', url: '/tr/p/wanda-soft-extra-automotion-kagit-havlu-4-kg', once: kaydir(700) },
  { ad: 'sepet', url: '/tr/sepet' },
  { ad: 'kampanyalar', url: '/tr/kampanyalar' },
  { ad: 'teklif-iste', url: '/tr/teklif-iste' },
  { ad: 'yardim', url: '/tr/yardim' },
  // Hesap
  { ad: 'ozet', url: '/tr/hesap/ozet' },
  { ad: 'ozet-alt', url: '/tr/hesap/ozet', once: kaydir(560) },
  { ad: 'siparisler', url: '/tr/hesap/siparisler' },
  { ad: 'siparis-hazirlaniyor', url: '/tr/hesap/siparisler/cmuwo1euv004b60vgufnvgnaz' },
  { ad: 'siparis-hazirlaniyor-alt', url: '/tr/hesap/siparisler/cmuwo1euv004b60vgufnvgnaz', once: kaydir(420) },
  { ad: 'siparis-taslak', url: '/tr/hesap/siparisler/cmuwo1i5v005w60vgu5fo3x2j' },
  { ad: 'siparis-odeme', url: '/tr/hesap/siparisler/cmuwo1htm005r60vg3687u49q' },
  { ad: 'siparis-onay', url: '/tr/hesap/siparisler/cmuwo1hhi005n60vgz9ty3fhl' },
  { ad: 'siparis-sevkiyat', url: '/tr/hesap/siparisler/cmuwo1dte003t60vgrstxfcbf' },
  { ad: 'hizli', url: '/tr/hesap/hizli-siparis' },
  { ad: 'periyodik', url: '/tr/hesap/periyodik-siparisler' },
  { ad: 'periyodik-yeni', url: '/tr/hesap/periyodik-siparisler', once: tikla('Yeni Şablon') },
  { ad: 'teklifler', url: '/tr/hesap/teklifler' },
  { ad: 'teklif-yeni', url: '/tr/hesap/teklifler', once: tikla('Yeni Teklif Talebi') },
  { ad: 'analitik', url: '/tr/hesap/analitik', bekle: 3000 },
  { ad: 'analitik-alt', url: '/tr/hesap/analitik', bekle: 3000, once: kaydir(560) },
  { ad: 'sozlesme', url: '/tr/hesap/sozlesme' },
  { ad: 'butce', url: '/tr/hesap/butce' },
  { ad: 'butce-alt', url: '/tr/hesap/butce', once: kaydir(380) },
  { ad: 'onaylarim', url: '/tr/hesap/onaylarim' },
  { ad: 'onay-kurallari', url: '/tr/hesap/onay-kurallari' },
  { ad: 'onay-kural-yeni', url: '/tr/hesap/onay-kurallari', once: tikla('+ Yeni Kural') },
  { ad: 'ekstre', url: '/tr/hesap/ekstre' },
  { ad: 'ekstre-alt', url: '/tr/hesap/ekstre', once: kaydir(380) },
  { ad: 'faturalar', url: '/tr/hesap/faturalar' },
  { ad: 'kullanicilar', url: '/tr/hesap/kullanicilar' },
  { ad: 'kullanici-davet', url: '/tr/hesap/kullanicilar', once: tikla('+ Kullanıcı Davet Et') },
  { ad: 'departmanlar', url: '/tr/hesap/departmanlar' },
  { ad: 'departman-yeni', url: '/tr/hesap/departmanlar', once: tikla('+ Yeni Departman') },
  { ad: 'projeler', url: '/tr/hesap/projeler' },
  { ad: 'proje-yeni', url: '/tr/hesap/projeler', once: tikla('Yeni Proje') },
  { ad: 'adresler', url: '/tr/hesap/adresler' },
  { ad: 'listeler', url: '/tr/hesap/listeler' },
  { ad: 'listeler-firma', url: '/tr/hesap/listeler?tab=COMPANY' },
  { ad: 'favoriler', url: '/tr/hesap/favoriler' },
  { ad: 'iadeler', url: '/tr/hesap/iadeler' },
  { ad: 'numune', url: '/tr/hesap/numune-talepler' },
  { ad: 'numune-yeni', url: '/tr/hesap/numune-talepler', once: tikla('+ Yeni Numune Talebi') },
  { ad: 'ai-oneri', url: '/tr/hesap/ai-oneri', bekle: 2500 },
  { ad: 'sadakat', url: '/tr/hesap/sadakat' },
  { ad: 'sadakat-alt', url: '/tr/hesap/sadakat', once: kaydir(560) },
  { ad: 'kuponlar', url: '/tr/hesap/kuponlar' },
  { ad: 'davet', url: '/tr/hesap/davet' },
  { ad: 'bildirimler', url: '/tr/hesap/bildirimler' },
  { ad: 'destek', url: '/tr/hesap/destek' },
  { ad: 'destek-yeni', url: '/tr/hesap/destek/yeni' },
  { ad: 'ayarlar', url: '/tr/hesap/ayarlar' },
  { ad: 'ayarlar-alt', url: '/tr/hesap/ayarlar', once: kaydir(560) },
];
